pingcap/pingcap.github.io

content/contact-us.md, layouts/page/contact-us.html, layouts/page/index.html, layouts/partials/layout/cta-footer.html, layouts/partials/layout/footer.html, layouts/partials/layout/header.html, layouts/partials/layout/mobile-sidebar.html, src/less/about.less, src/less/cases.less, src/less/doc.less, src/less/hero.less
This branch was to add a Contact Us form to the footer on the EN site. I made a few changes:
1. I changed the footer title, `Contact` to `Connect`
2. Under Company, I added a link `Contact Us` --> this points to a form I created on HubSpot. The form fills should go directly into the HubSpot CRM we are testing. 
Note: When testing via NPM start, the Contact Us page did not load. Please check if there is an issue.
=> Contact us

content/recruit-cn/i18n/technical-writer.md
=> Fix technical writer format

data/pingcapers.json
=> data: modify pingcapers

layouts/recruit-cn/list.html
=> layouts/recruit-cn:modify collaboration

data/hacker_culture.json
=> data: modify the contents of hacker culture

layouts/page/index-cn.html
update TiDB introduction in index-cn.html
=> update content in index-cn.html

layouts/partials/layout/footer.html, src/less/footer.less
=> udpate footer position

data/success_stories.json
=> data: fix a typo in success stories

data/news.json
=> data: add infoworld bossie award news

content/community.md, layouts/page/community.html, layouts/page/tidb-academy.html, layouts/page/tidb-cloud.html, layouts/partials/layout/footer.html, src/less/cases.less
=> add English community page

layouts/partials/layout/mobile-sidebar.html, layouts/partials/tidb-academy/navbar.html, layouts/tidb-academy/list.html, src/js/app.js, src/less/tidb-academy/profile.less, static/js/vendor/login.js
=> fix hamburger click bugs

layouts/tidb-academy/list.html
=> update iframe width in welcome page

layouts/page/index.html
=> layouts/page/index: update ETL description

data/news.json
=> data: add infoworld TiDB OLTP/OLAP news

layouts/tidb-academy/list.html, src/less/tidb-academy/profile.less
=> add tidb academy introduction content in tidb academy welcome page

data/release.json, layouts/_default/baseof.tpl.html, layouts/partials/layout/release-banner.html
=> add PingCAP University release banner

content/recruit-cn/TOC.md, content/recruit-cn/campus/campus-2019-content-strategist.md, content/recruit-cn/campus/content-strategist-intern.md, content/recruit-cn/i18n/Content-Strategist.md
=> content/recruit-cn: rename the title of technical writer to content strategist

content/recruit-cn/TOC.md, content/recruit-cn/campus/campus-2019-content-strategist.md, content/recruit-cn/campus/content-strategist-intern.md, content/recruit-cn/i18n/content-strategist.md
=> content/recruit-cn: rename technical writer to content strategist

layouts/page/about-cn.html
=> replace pingcap intro video in about-cn

src/less/doc.less
=> adjust label text align and add continue arrow

content/recruit-cn/TOC.md, content/recruit-cn/business/channel-sales-director.md
=> content/recruit-cn/business:rename channel-co-director to channel-sales-director

content/recruit-cn/TOC.md
=> content/recruit-cn：fix a spelling mistake in “specialist”

src/js/app.js
=> fix bug in carousel section input check

scripts/convert_html.py
=> scripts/convert_html: compress html by using unicode method

layouts/docs-cn/list.html, layouts/docs/list.html
=> remove Download PDF entry from docs and docs-cn.

Makefile, config.toml, data/cases_cn_toc.json, data/recruit_cn_toc.json, data/sub_git_info.json, layouts/docs/list.html, layouts/docs/single.html, layouts/partials/archives/sticky-tree.html, layouts/partials/navs/version-nav.html, package-lock.json, src/less/sidebar.less
**Warning**: Do *not* merge this just yet. I'll provide a go-ahead when it's ready.
cc @lilin90 @queenypingcap
=> Docs version switcher

layouts/docs/single.html
=> change parameter $version to $versions

layouts/partials/layout/cta-footer-cn.html, layouts/partials/layout/header-cn.html, layouts/partials/layout/mobile-sidebar-cn.html
=> change item name and link in nav-cn

src/less/community/devcon2019.less
=> fix table td vertical align

layouts/community/devcon2019.html, src/js/devcon.js, src/less/community/devcon2019.less
=> fix devcon navbar burger

data/devcon2019.json
=> update instructor's company name

data/devcon2019.json, layouts/community/devcon2019.html, src/less/community/devcon2019.less
=> adjust card height and fix content typo

layouts/community/devcon2019.html
=> update title capitalization

data/devcon2019.json, layouts/community/devcon2019.html
=> update company name

layouts/community/devcon2019.html
=> update meta title and add a period

layouts/community/devcon2019.html
=> add a space between '-' and a word

layouts/partials/layout/header-cn.html, layouts/partials/layout/mobile-sidebar-cn.html
=> expose devcon 2019 entries

layouts/blog-cn/list.html, layouts/blog-cn/single.html, layouts/blog/list.html, layouts/blog/single.html, layouts/meetup/archive.html, layouts/meetup/single.html, layouts/recruit-cn/single.html, layouts/tidb-academy/list.html, layouts/tidb-academy/single.html, layouts/weekly/list.html, layouts/weekly/single.html
=> add clipboardjs for each file, which imports doc.js

layouts/blog-cn/list.html, layouts/blog-cn/single.html, layouts/blog/list.html, layouts/blog/single.html, layouts/meetup/archive.html, layouts/meetup/single.html, layouts/recruit-cn/single.html, layouts/tidb-academy/list.html, layouts/tidb-academy/single.html, layouts/weekly/list.html, layouts/weekly/single.html
Reverts pingcap/pingcap.github.io#128
=> Revert "add clipboardjs for each file, which imports doc.js"

content/recruit-cn/TOC.md, content/recruit-cn/engineering/olap-engineer.md
=> content/recruit-cn/engineering: rename tispark engineer

layouts/community/devcon2019.html
=> update bilibili's company name

layouts/blog-cn/list.html, layouts/blog-cn/single.html
=> add category: community reading

src/js/devcon.js
=> fix devcon instructor card hover and click issue

layouts/community/devcon2019.html
=> add an agenda

scripts/gen-contributors.js
=> chore: update git repos for generation contributors

layouts/tidb-planet/release-notes.html, src/js/tidb_planet.js
=> replace tidb-planet video and check relase notes link

layouts/tidb-planet/release-notes.html
=> update release notes content

layouts/community-cn/devcon2019.html, layouts/partials/layout/devcon-nav.html, src/less/community/devcon2019.less
=> remove outdate information of devcon2019

layouts/community-cn/organization.html
=> fix broken image in community organization page

layouts/community-cn/organization.html
=> replace tidb planet image in community organization

layouts/blog/list.html, layouts/partials/navs/blog-category-nav.html, src/less/blog.less
=> update blog category and size of tutorial logos

src/less/community/devcon2019.less
=> replace devcon banner with high quality image

data/news_cn.json
=> add two news_cn

content/recruit-cn/engineering/bizdev-sa-engineer.md
=> content/recruit-cn/engineering: add title of sa

layouts/docs-cn/list.html, layouts/docs/list.html
=> expose PDF generation entry

scripts/gen-content.sh
=> generate docs/docs-nav sidebar toc by reading TOC.md

scripts/process-docs.sh
=> chore: process cases-cn images

layouts/partials/layout/footer.html, layouts/partials/layout/mobile-sidebar.html
=> change 'Subscritbe' to 'Subscribe to Blog'

layouts/community-cn/list.html, layouts/partials/archives/article-reading-card.html, src/less/article-reading-card.less, src/less/blog.less
=> make blog article reading card reusable

.circleci/config.yml
=> circleci/config.yml: remove command 'sudo apt-get update'

layouts/_default/baseof.tpl.html, layouts/page/index-cn.html, layouts/partials/layout/cta-footer-cn.html, layouts/partials/layout/footer-cn.html, layouts/partials/layout/header-cn.html, layouts/partials/tracking-code/ga-events-js.html
=> set buttons track in homepage

src/js/app.js
=> src/js/app.js: remove language filtering for docs search result

src/js/app.js
=> polish: update docsearch api config params

src/less/main.less
=> chore: hide the category-header display temporary

src/less/main.less
=> chore: show the category-header in hits suggestions

layouts/partials/layout/recording-share.html, layouts/partials/layout/video-on-modal.html, src/js/video_on_modal.js
=> fix video autoplay on modal

layouts/community-cn/hackathon2018.html, src/js/devcon.js, src/less/community/hackathon2018.less
=> hackathon2018.html: fix overlay display when clicks card

layouts/partials/layout/video-on-modal.html, src/js/video_on_modal.js
=> fix: fix video can not play in mobile issue

src/js/app.js, src/less/main.less
=> polish: add hitsPerPage value to 50

data/hackathon2018.json, data/meetup.json, data/techday2018.json, layouts/community-cn/devcon2019.html, layouts/community-cn/hackathon2018.html, layouts/community-cn/organization.html, layouts/meetup/list.html, src/js/carousel.js, src/less/community/common-style.less, src/less/community/hackathon2018.less, src/less/community/instructors.less, src/less/community/techday2018.less, src/less/meetup.less
=> upload images and videos to CDN

src/js/video_on_modal.js
=> chore: change video play logic in mobile devices

layouts/community-cn/hackathon2018.html
=> update hackathon 2017 review thumbnail image

layouts/partials/maps/world-map.html
=> chore: update offices information

data/release.json, layouts/partials/layout/release-banner.html
=> update homepage banner to slack channel

layouts/partials/layout/release-banner.html
=> remove square brackets from banner

data/meetup.json, layouts/community-cn/list.html, layouts/partials/layout/meetup-carousel.html, src/js/carousel.js, src/js/community.js, src/js/multi_slides_carousel.js
=> update next meetup

layouts/community-cn/list.html
=> fix activity link in calendar

layouts/meetup/list.html
=> sort meetup content by date reverse and alphabetical of title

data/news.json
=> data: add saving time with TiDB post

data/hackathon2018.json, layouts/community-cn/hackathon2018.html, src/less/community/common-style.less, src/less/community/hackathon2018.less
=> fix broken links

layouts/meetup/list.html
=> remove invalid link

src/js/doc.js
=> update the Chinese Note in blockqupte

layouts/tidb-planet/user.html
=> update relative path of user-info

.circleci/config.yml
=> config.yml: replace trigger branch

layouts/blog/single.html, layouts/partials/tracking-code/ga-events-js.html, src/less/doc.less
=> blog/single.html: add button click tracker

layouts/blog/single.html, src/less/doc.less
=> blog/single.html: add smart side toc

layouts/blog/single.html, src/less/doc.less
=> blog/single.html: update toc layout

src/less/doc.less
=> doc.less: set max width to sidebar-toc

data/release.json
The previous link is now broken.
=> Updated functional Slack link

layouts/community-cn/devcon2018.html
=> devcon2018.html: add video poster

layouts/community-cn/devcon2018.html, layouts/community-cn/techday2018.html, src/less/community/devcon2019.less, src/less/community/techday2018.less
=> update modal css

src/less/community/list.less
=> community/list.less: update section margin in hackthon2018

src/less/community/hackathon2018.less, src/less/community/list.less
=> hackathon2018.html: update margin of project card

data/techday.json, layouts/community-cn/techday2017.html, layouts/community-cn/techday2018.html, src/less/community/hackathon2018.less, src/less/community/instructors.less
=> community-cn: update content

src/less/community/instructors.less
=> community/instructors.less: update card margin

content/tidb-slack.md, data/release.json, layouts/page/index.html, layouts/page/tidb-slack.html
=> feature: make a url to redirect user to the TiDB Community Slack channel

layouts/partials/navs/tree-nav.html, src/less/sidebar.less
=> tree-nav.html: add code style to side bar

layouts/page/community.html
=> layouts/page: fix a typo

layouts/community-cn/organization.html, scripts/gen-contributors.js, src/less/doc.less
=> add TiDB-binlog to TiDB planet

layouts/partials/layout/header-cn.html, layouts/partials/layout/mobile-sidebar-cn.html
=> header-cn.html: expose PingCAP University Entry

.circleci/config.yml, static/robots.txt
- declare sitemap in robots.txt
- notify google after website publishing
=> seo by sitemap

data/meetup.json
=> meetup.json: add a missing image

static/robots.txt
=> robots.txt: remove disallowed crawling versions

.gitignore
This reverts commit c72e85e317a6a9999086586f923aa75db543dda0.
=> Revert "cleanup: ignore submodules folders (#255)"

data/meetup.json
=> update banner 20190521

data/meetup.json
=> update banner 20190527

.circleci/config.yml
=> .circleci/config.yml: comment publish github.io

scripts/process-docs.sh
- fix the bug which processes all html files twice
- pre-judge by grep to avoid open unnecessary html file by python
=> chore: polish the build config to reduce the build time

data/news.json
=> data: add TiDB 3.0 announcement post

data/meetup.json
=> update banner 20190606

layouts/page/index.html, scripts/process-docs.sh, src/js/doc.js
=> fixed: images cannot show on meetup page

data/techday.json, layouts/community-cn/techday2019.html, layouts/partials/community-cn/techday-schedule-table.html, src/less/community/common-style.less, src/less/community/techday-agenda.less, src/less/community/techday.less
=> add signup link

data/techday.json, src/less/community/techday.less
=> add techday schedule

data/techday.json, layouts/community-cn/techday2019.html, src/less/community/techday-agenda.less
=> update content and agenda table

layouts/docs/list.html
=> fix: update doc list page

layouts/page/index-cn.html, src/js/multi_slides_carousel.js, src/less/index.less
=> index_cn.html: add carousel for techday and unvierstiy

data/techday.json, layouts/page/index-cn.html
=> techday: replace image order

layouts/page/index-cn.html
=> index_cn.html: update image url

data/techday.json, layouts/page/index-cn.html, src/js/carousel.js, src/js/multi_slides_carousel.js, src/less/index.less
=> update agenda and replace some images

src/less/index.less
=> update banner display on big screen

data/news_cn.json, layouts/meetup/list.html, layouts/meetup/single.html
=> fixed: update two broken links

data/techday.json
=> techday.json: update techday agenda

data/meetup.json
=> update banner 20190619

data/community_activities.json, data/techday.json, layouts/community-cn/list.html
=> add techday agenda to calendar

data/release.json, layouts/_default/baseof.tpl.html, layouts/partials/layout/release-banner.html
=> add PingCAP university signup form entry

layouts/_default/baseof.tpl.html
=> baseof.tpl.html: add release banner only on index page

data/techday.json, layouts/docs-cn/list.html
=> techday.json: update agenda

data/news.json
=> data: add a post of The KOST Stack

layouts/community-cn/techday2019.html, layouts/docs-cn/list.html, layouts/partials/community-cn/techday-schedule-tab.html, layouts/partials/community-cn/techday-schedule-table.html
=> update techday 2019 agenda

layouts/partials/archives/download-pdf.html
=> download-pdf.html: update download-pdf link

data/success_stories.json
@lilian90 PTAL 
@queenypingcap FYI.
=> data: remove iQiyi user statistics

layouts/docs-cn/list.html, layouts/docs/list.html, layouts/partials/archives/download-pdf.html
=> fixed: version switch bug

data/techday.json
=> techday.json: add new techday agenda

data/techday.json
=> techday2019.json: add new techday agenda

data/techday.json, layouts/community-cn/list.html, layouts/partials/archives/download-pdf.html, src/js/app.js, src/js/community.js, src/less/community/list.less, src/less/community/techday-agenda.less
=> update techday agenda and PDF

layouts/docs-cn/list.html, layouts/docs/list.html
=> update content in docs/docs-cn landing page

layouts/partials/layout/footer-cn.html, layouts/partials/layout/footer.html
=> layouts/partials/layout: fix 2 links

src/js/doc.js, src/js/vendor/jquery.SimpleTree.js
=> enable sidebar scroll to active toc when visiting a url contains hash

layouts/community-cn/devcon2018.html, layouts/community-cn/devcon2019.html, layouts/community-cn/hackathon2018.html, layouts/community-cn/list.html, layouts/community-cn/techday2017.html, layouts/community-cn/techday2018.html, layouts/community-cn/techday2019.html, layouts/docs-cn/single.html, layouts/docs/single.html
1. make language switcher in docs/docs-cn pages jump to docs-cn/doc landing page.
2. make language switcher in community-cn/* pages jump to community/organization page.
PTAL
=> update language switcher

data/meetup.json
=> Update banner 20190724 

layouts/tidb-cloud/list.html
Do we have a preview for these changes? I have errors from node when trying to run this locally.
=> tidb-cloud: remove marketplace section

layouts/partials/layout/footer.html
=> layouts/partials: fix Quick Start link

layouts/about-cn/recruit/join.html, layouts/page/index-cn.html, src/less/index.less
1. add an image in Chinese homepage for 2020 campus recruit entry.
2. add JS to detect the hash and make corresponded tab checked.
PTAL
=> Add 2020 campus recruit

layouts/shortcodes/tabs-panel.html, src/less/doc.less
=> add shortcode for letters tabs panel used in docs

data/techday.json, layouts/community-cn/devcon2018.html, layouts/community-cn/devcon2019.html, layouts/community-cn/hackathon2018.html, layouts/community-cn/techday2017.html, layouts/community-cn/techday2018.html, layouts/community-cn/techday2019.html, layouts/meetup/list.html, layouts/page/index-cn.html, layouts/partials/community-cn/site-record.html, layouts/partials/community-cn/techday-schedule-table.html, src/js/multi_slides_carousel.js, src/less/community/devcon2019.less, src/less/tidb-planet/modal.less
=> add review videos to techday 2019

data/techday.json, layouts/community-cn/techday2019.html, layouts/partials/community-cn/techday-schedule-table.html, layouts/partials/layout/multi_slides_carousel.html, src/js/multi_slides_carousel.js, src/less/community/multi-slides-carousel.less, src/less/community/techday-agenda.less, src/less/meetup.less
=> Add review videos to each city

layouts/community-cn/techday2019.html, layouts/page/index-cn.html, layouts/partials/layout/multi_slides_carousel.html, src/js/multi_slides_carousel.js, src/less/community/multi-slides-carousel.less
=> Add mobile carousel

data/success_stories.json
=> data: remove periods

scripts/convert_html.py
=> remove docs version prefix

data/news.json
=> data: add Zhihu's news on DZone

data/news.json
@YiniXu9506 It's a broken link. So I remove this news.
=> data: remove invalid news

data/news.json
=> data: add Building a Distributed Storage System Based on Raft

.circleci/config.yml, layouts/partials/head/meta-seo.html, scripts/consolidate-duplicate-urls.sh, scripts/convert_html.py
=> consolidate duplicate URLs

data/news.json
=> data: add the Raft post on DZone in news

data/news.json
=> data: add the vectorized execution post

data/success_stories.json
=> data: add the industry category for NetEase Games

data/news.json
=> data: add AutoTiKV

config.toml
=> add new version

layouts/_default/baseof.tpl.html, layouts/partials/layout/footer-cn.html, layouts/partials/layout/footer.html, layouts/partials/layout/mobile-sidebar-cn.html, layouts/partials/layout/mobile-sidebar.html, src/js/app.js, src/js/mailchimp.js, src/less/index.less
=> fix: fix the same mailchimp form id in both mobile and pc pages

content/about-cn/recruit/TOC.md
=> add new position

data/news.json
=> data: add the TiDB Dashboard post in news

.gitmodules, content/search/docs/dev.md, content/search/docs/stable.md, content/search/docs/tidb-data-migration/dev.md, content/search/docs/tidb-data-migration/stable.md, content/search/docs/tidb-in-kubernetes/dev.md, content/search/docs/tidb-in-kubernetes/stable.md, content/search/docs/tidb-in-kubernetes/v1.0.md, content/search/docs/v2.1.md, content/search/docs/v3.0.md, content/search/docs/v3.1.md, content/search/docs/v4.0.md, scripts/consolidate-duplicate-urls.sh, scripts/gen-content.sh, scripts/process-docs.sh
=> Stop building docs

data/news.json
=> data: add the Cluster Diagnostics news

data/news.json
=> data: add six news

webpack.config.js
- remove object.fromEntries since it's not supported on node.js ver 8.x
=> chore: update webpack entries
